Repository ISTTP/K-KOO, pull requests merged in 2024-08, with the labels that each got.

#74 내가 작성한 편지함을 구현한다.
  apps/client/package.json
  apps/client/src/App.tsx
  apps/client/src/apis/cake/useGetCakeLetters.tsx
  apps/client/src/apis/cake/useGetGridLetters.tsx
  apps/client/src/apis/cake/useGetYear.tsx
  apps/client/src/apis/letter/useGetLetter.tsx
  apps/client/src/apis/letter/useGetMyLetters.tsx
  apps/client/src/components/cake/CakeInfo.tsx
  apps/client/src/components/cake/GridInfo.tsx
  apps/client/src/components/cake/GridStyle.tsx
  apps/client/src/components/common/YearDropDown.tsx
  apps/client/src/pages/MyLetter.tsx
  apps/client/src/pages/MyPage.tsx
  apps/client/src/styles/GridStyle.tsx
  apps/server/src/routes/letter.ts
  packages/schemas/src/letter/requests.ts
Labels: 🐛 Bug, ✨ Feature

#75 유저는 자체 로그인을 할 수 있다.
  apps/client/package.json
  apps/client/src/App.css
  apps/client/src/App.tsx
  apps/client/src/apis/axios.ts
  apps/client/src/components/cake/ColorSelector.tsx
  apps/client/src/components/cake/SharedCake.tsx
  apps/client/src/components/common/Button.tsx
  apps/client/src/components/common/Timer.tsx
  apps/client/src/components/signup/BirthdayForm.tsx
  apps/client/src/components/signup/EmailForm.tsx
  apps/client/src/components/signup/IdForm.tsx
  apps/client/src/components/signup/NicknameForm.tsx
  apps/client/src/components/signup/PasswordForm.tsx
  apps/client/src/environment.d.ts
  apps/client/src/pages/Login.tsx
  apps/client/src/styles/SignUpStyle.ts
  apps/client/src/utils/checkBirthdayWithin30Days.ts
  apps/client/src/utils/handleButtonClick.ts
  apps/client/src/utils/hashPassword.ts
  apps/client/src/utils/index.ts
  apps/server/src/environment.d.ts
  apps/server/src/models/user.ts
  apps/server/src/models/verify.ts
  apps/server/src/routes/auth.ts
  apps/server/src/routes/user.ts
  apps/server/src/routes/verify.ts
  apps/server/src/service/auth.ts
  packages/types/src/button.ts
  packages/types/src/index.ts
  pnpm-lock.yaml
Labels: 🖼️ Design, 📦 Chore, ✨ Feature

#76 케이크 페이지 스타일을 추가한다.
  apps/client/src/Normalize.css
  apps/client/src/apis/letter/useGetLetter.tsx
  apps/client/src/assets/icons/CakeIcon.tsx
  apps/client/src/assets/icons/GridIcon.tsx
  apps/client/src/assets/icons/PenIcon.tsx
  apps/client/src/assets/icons/index.ts
  apps/client/src/components/cake/CakeInfo.tsx
  apps/client/src/components/cake/GridInfo.tsx
  apps/client/src/components/cake/Pagenation.tsx
  apps/client/src/components/common/Toggle.tsx
  apps/client/src/components/common/YearDropDown.tsx
  apps/client/src/components/layout/InnerWrapper.tsx
  apps/client/src/components/layout/Wrapper.tsx
  apps/client/src/components/letter/ReadLetter.tsx
  apps/client/src/pages/MyLetter.tsx
Labels: 🐛 Bug, 🖼️ Design

#78 PC뷰를 위한 sidebar를 구현한다.
  apps/client/package.json
  apps/client/public/index.html
  apps/client/src/ModalPortal.ts
  apps/client/src/Normalize.css
  apps/client/src/assets/icons/CakeLogo.tsx
  apps/client/src/assets/icons/DropDownIcon.tsx
  apps/client/src/assets/icons/GridIcon.tsx
  apps/client/src/assets/icons/PenIcon.tsx
  apps/client/src/assets/icons/PersonIcon.tsx
  apps/client/src/assets/icons/ShareIcon.tsx
  apps/client/src/assets/icons/index.ts
  apps/client/src/components/cake/CakeHeader.tsx
  apps/client/src/components/cake/CakeInfo.tsx
  apps/client/src/components/cake/GridInfo.tsx
  apps/client/src/components/cake/MyCake.tsx
  apps/client/src/components/cake/RenderCake.tsx
  apps/client/src/components/cake/Sidebar.tsx
  apps/client/src/components/common/Toggle.tsx
  apps/client/src/components/common/YearDropDown.tsx
  apps/client/src/components/layout/InnerWrapper.tsx
  apps/client/src/components/layout/Wrapper.tsx
  apps/client/src/components/letter/ReadLetter.tsx
  apps/client/src/components/modal/Modal.tsx
  apps/client/src/hooks/useIsPc.tsx
  apps/client/src/pages/Cake.tsx
  apps/client/src/pages/CreateLetter.tsx
  apps/client/src/store/useTestStore.ts
  apps/client/src/store/useToggleStore.ts
  apps/client/src/styles/GridStyle.tsx
  apps/client/src/styles/SidebarStyle.tsx
  apps/server/src/routes/letter.ts
  packages/schemas/src/letter/responses.ts
  pnpm-lock.yaml
Labels: 🖼️ Design, ✨ Feature

#80 modal portal을 적용한다.
  apps/client/src/assets/icons/ShareIcon.tsx
  apps/client/src/components/cake/CakeInfo.tsx
  apps/client/src/components/cake/GridInfo.tsx
  apps/client/src/components/cake/SharedCake.tsx
  apps/client/src/components/cake/Sidebar.tsx
  apps/client/src/components/letter/ReadLetter.tsx
  apps/client/src/components/modal/Modal.tsx
  apps/client/src/styles/SidebarStyle.tsx
Labels: 🖼️ Design, ✨ Feature

#81 케이크 조회, 수정 페이지 디자인
  apps/client/src/App.css
  apps/client/src/components/cake/CakeHeader.tsx
  apps/client/src/components/cake/CakeInfo.tsx
  apps/client/src/components/cake/ColorSelector.tsx
  apps/client/src/components/cake/RenderCake.tsx
  apps/client/src/components/cake/SharedCake.tsx
  apps/client/src/pages/CreateCake.tsx
Labels: 🖼️ Design

#83 장식초 선택, 편지 작성, 마이페이지 디자인
  apps/client/src/App.css
  apps/client/src/pages/ChooseCandle.tsx
  apps/client/src/pages/CreateLetter.tsx
  apps/client/src/pages/MyPage.tsx
  apps/client/src/styles/MyPageStyle.ts
  apps/server/src/models/candle.ts
  packages/database/prisma/schema.prisma
Labels: 🖼️ Design

#84 생일 당일일 경우 축하 팡파레가 보인다.
  apps/client/package.json
  apps/client/public/apple-icon.png
  apps/client/public/favicon.png
  apps/client/src/App.css
  apps/client/src/assets/fonts/Sansita-ExtraBoldItalic.ttf
  apps/client/src/components/cake/MyCake.tsx
  apps/client/src/components/cake/Pagenation.tsx
  apps/client/src/components/cake/RenderCake.tsx
  apps/client/src/components/cake/SharedCake.tsx
  apps/client/src/components/common/Tooltip.tsx
  apps/client/src/components/layout/InnerWrapper.tsx
  apps/client/src/pages/Cake.tsx
  apps/client/src/utils/checkBirthdayWithin30Days.ts
  apps/client/src/utils/index.ts
  apps/server/src/routes/cake.ts
  apps/server/src/service/letter.ts
  packages/schemas/src/cake/responses.ts
  packages/schemas/src/user/responses.ts
  packages/types/src/cake.ts
  pnpm-lock.yaml
Labels: ✨ Feature

#85 디자인 추가 작업을 진행한다.
  apps/client/package.json
  apps/client/public/apple-icon.png
  apps/client/public/favicon.png
  apps/client/src/App.css
  apps/client/src/assets/fonts/Sansita-ExtraBoldItalic.ttf
  apps/client/src/components/cake/MyCake.tsx
  apps/client/src/components/cake/Pagenation.tsx
  apps/client/src/components/cake/RenderCake.tsx
  apps/client/src/components/cake/SharedCake.tsx
  apps/client/src/components/common/Tooltip.tsx
  apps/client/src/components/layout/InnerWrapper.tsx
  apps/client/src/pages/Cake.tsx
  apps/client/src/pages/ChooseCandle.tsx
  apps/client/src/pages/CreateLetter.tsx
  apps/client/src/pages/MyPage.tsx
  apps/client/src/styles/MyPageStyle.ts
  apps/client/src/utils/checkBirthdayWithin30Days.ts
  apps/client/src/utils/index.ts
  apps/server/src/models/candle.ts
  apps/server/src/routes/cake.ts
  apps/server/src/service/letter.ts
  packages/database/prisma/schema.prisma
  packages/schemas/src/cake/responses.ts
  packages/schemas/src/user/responses.ts
  packages/types/src/cake.ts
  pnpm-lock.yaml
Labels: 🖼️ Design

#88 bundleanalyzer를 제거한다.
  apps/client/webpack.config.prod.js
Labels: 📦 Chore

#90 케이크 이미지 주소 webp로 변환
  .vscode/settings.json
  apps/client/src/components/cake/RenderCake.tsx
Labels: ✨ Feature

#91 케이크 이미지 주소 webp로 변환
  .vscode/settings.json
  apps/client/src/components/cake/RenderCake.tsx
Labels: ✨ Feature

#92 케이크이미지 avif로 형변환
  apps/client/src/components/cake/RenderCake.tsx
Labels: 🔥Performance

#93 케이크이미지 avif로 형변환
  apps/client/src/components/cake/RenderCake.tsx
Labels: 🔥Performance

#94 반응형 이미지 제공, S3 주소 preconnect 제공
  apps/client/public/index.html
  apps/client/src/components/cake/RenderCake.tsx
Labels: 🔥Performance

#95 반응형 이미지 제공, S3 주소 preconnect 제공
  apps/client/public/index.html
  apps/client/src/components/cake/RenderCake.tsx
Labels: 🔥Performance
