Repository ISTTP/K-KOO, pull requests merged in 2024-07, with the labels that each got.

#15 Feature/google_login 기능 구현 중간 PR
  .github/workflows/mainDeploy.yml
  apps/client/config/instrument.d.ts
  apps/client/config/instrument.d.ts.map
  apps/client/config/instrument.js
  apps/client/package.json
  apps/client/src/App.tsx
  apps/client/src/pages/GoogleLogin.tsx
  apps/client/src/pages/Login.tsx
  apps/client/tsconfig.json
  apps/client/webpack.config.dev.js
  apps/server/Dockerfile
  apps/server/src/index.ts
  apps/server/src/routes/auth.ts
  docker-compose.yml
  packages/types/src/auth.ts
  packages/types/src/index.ts
  pnpm-lock.yaml
Labels: 📦 Chore, ✨ Feature

#17 카카오 로그인 구현 중 인가코드, 토큰을 발급받다.
  apps/client/src/App.tsx
  apps/client/src/apis/axios.ts
  apps/client/src/pages/KakaoLogin.tsx
  apps/client/src/pages/Login.tsx
  apps/client/webpack.config.dev.js
  apps/server/package.json
  apps/server/src/index.ts
  apps/server/src/routes/auth.ts
  packages/types/src/auth.ts
  pnpm-lock.yaml
Labels: ✨ Feature

#18 소셜 로그인, 회원가입 후 토큰을 발급해주고 케이크 페이지로 이동한다.
  .vscode/settings.json
  apps/client/src/App.tsx
  apps/client/src/pages/Cake.tsx
  apps/client/src/pages/GoogleLogin.tsx
  apps/client/src/pages/KakaoLogin.tsx
  apps/client/src/pages/Login.tsx
  apps/client/src/pages/Signup.tsx
  apps/client/webpack.config.prod.js
  apps/server/package.json
  apps/server/src/routes/auth.ts
  apps/server/src/server.ts
  packages/database/prisma/schema.prisma
  packages/types/src/auth.ts
  packages/utils/package.json
  packages/utils/src/index.ts
  packages/utils/src/jwt.ts
  pnpm-lock.yaml
Labels: 📦 Chore, ✨ Feature

#20 scope명을 변경하고 JIT 패키지 방식으로 수정한다.
  apps/client/.eslintrc.js
  apps/client/package.json
  apps/client/src/components/__tests__/Button.test.tsx
  apps/client/src/pages/KakaoLogin.tsx
  apps/client/src/test/example.test.tsx
  apps/client/tsconfig.json
  apps/server/.eslintrc.js
  apps/server/package.json
  apps/server/src/routes/auth.ts
  apps/server/tsconfig.json
  packages/database/.eslintrc.js
  packages/database/package.json
  packages/database/tsconfig.json
  packages/eslint-config/package.json
  packages/jest-presets/package.json
  packages/types/.eslintrc.js
  packages/types/package.json
  packages/types/tsconfig.json
  packages/typescript-config/package.json
  packages/utils/package.json
  packages/utils/tsconfig.json
  pnpm-lock.yaml
Labels: 🔧 Refator

#21 db:generate 명령어 전역 추가
  package.json
Labels: 📦 Chore

#22 path alias를 적용한다.
  apps/client/package.json
  apps/client/src/App.tsx
  apps/client/src/components/Button.tsx
  apps/client/src/pages/Cake.tsx
  apps/client/src/pages/GoogleLogin.tsx
  apps/client/src/pages/KakaoLogin.tsx
  apps/client/src/pages/Login.tsx
  apps/client/src/pages/Signup.tsx
  apps/client/src/test/example.test.tsx
  apps/client/tsconfig.json
Labels: 🔧 Refator

#23 github actions env 설정을 변경한다.
  .github/workflows/mainDeploy.yml
Labels: 📦 Chore

#25 docker-compose.yml에서 env_file 삭제
  docker-compose.yml
Labels: 📦 Chore

#27 패키지 import 문제 해결을 위해 references 옵션을 적용한다.
  .github/workflows/mainDeploy.yml
  .gitignore
  apps/server/package.json
  apps/server/tsconfig.json
  packages/database/package.json
  packages/database/tsconfig.json
  packages/utils/package.json
  packages/utils/tsconfig.json
Labels: 🐛 Bug

#28 패키지 import 오류 수정
  .github/workflows/mainDeploy.yml
  .gitignore
  apps/server/package.json
  apps/server/tsconfig.json
  packages/database/package.json
  packages/database/tsconfig.json
  packages/utils/package.json
  packages/utils/tsconfig.json
Labels: 🐛 Bug

#29 github actions env를 ssh에 추가한다.
  .github/workflows/mainDeploy.yml
Labels: 📦 Chore

#30 github actions 배포 과정 중 ssh에 환경변수를 주입한다.
  .github/workflows/mainDeploy.yml
Labels: 📦 Chore

#31 유저 토큰 검증 API 추가
  apps/client/.eslintrc.js
  apps/client/src/apis/axios.ts
  apps/client/src/pages/KakaoLogin.tsx
  apps/server/package.json
  apps/server/src/index.ts
  apps/server/src/routes/auth.ts
  apps/server/src/routes/user.ts
  apps/server/src/server.ts
  apps/server/tsconfig.json
  packages/utils/package.json
  packages/utils/src/jwt.ts
  pnpm-lock.yaml
Labels: ✨ Feature

#32 PR리뷰 후 1차 보완
  .vscode/settings.json
  apps/client/package.json
  apps/client/src/App.tsx
  apps/client/src/components/Button.tsx
  apps/client/src/enviroment.d.ts
  apps/client/tsconfig.json
  apps/server/Dockerfile
  apps/server/package.json
  apps/server/src/enviroment.d.ts
  apps/server/src/routes/auth.ts
  apps/server/src/routes/user.ts
  apps/server/src/server.ts
  apps/server/tsconfig.json
  package.json
  packages/database/package.json
  packages/database/tsconfig.json
  packages/eslint-config/package-lock.json
  packages/eslint-config/package.json
  packages/eslint-config/react.js
  packages/jest-presets/package.json
  packages/types/.eslintrc.js
  packages/types/package.json
  packages/types/src/enviroment.d.ts
  packages/types/src/index.ts
  packages/types/tsconfig.json
  packages/typescript-config/base.json
  packages/typescript-config/package.json
  packages/typescript-config/react.json
  packages/utils/package.json
  packages/utils/src/enviroment.d.ts
  packages/utils/src/jwt.ts
  packages/utils/tsconfig.json
  pnpm-lock.yaml
  turbo.json
Labels: 📦 Chore

#35 유저 아이디 타입 변경, 생성 로직 추가
  apps/server/src/models/user.ts
  apps/server/src/routes/auth.ts
  apps/server/src/service/auth.ts
  packages/database/prisma/schema.prisma
  packages/types/src/jwt.ts
  packages/utils/src/jwt.ts
Labels: ✨ Feature

#36 케이크 페이지 중 토글, 편지리스트 조회, 페이지네이션을 구현한다.
  .vscode/settings.json
  apps/client/package.json
  apps/client/src/components/CakeInfo.tsx
  apps/client/src/components/GridInfo.tsx
  apps/client/src/components/Pagenation.tsx
  apps/client/src/components/Toggle.tsx
  apps/client/src/pages/Cake.tsx
  apps/server/src/index.ts
  apps/server/src/routes/cake.ts
  packages/types/src/cake.ts
  packages/types/src/index.ts
  pnpm-lock.yaml
Labels: ✨ Feature

#37 케이크 페이지의 버전을 구분해 보여준다.
  apps/client/src/App.tsx
  apps/client/src/components/cake/CakeInfo.tsx
  apps/client/src/components/cake/MyCake.tsx
  apps/client/src/components/cake/Pagenation.tsx
  apps/client/src/components/cake/SharedCake.tsx
  apps/client/src/pages/Cake.tsx
  apps/client/src/pages/GoogleLogin.tsx
  apps/client/src/pages/KakaoLogin.tsx
  apps/client/src/pages/Signup.tsx
  apps/server/src/routes/auth.ts
  apps/server/src/routes/cake.ts
  apps/server/src/service/auth.ts
  packages/database/prisma/schema.prisma
  packages/types/src/cake.ts
Labels: ✨ Feature

#38 api 요청 권한 검증 로직을 수정한다.
  apps/server/src/routes/user.ts
  apps/server/src/service/auth.ts
Labels: 🔧 Refator

#39 인가 middleware 적용한다.
  apps/client/src/pages/Cake.tsx
  apps/server/src/enviroment.d.ts
  apps/server/src/routes/user.ts
  apps/server/src/service/auth.ts
Labels: 🔧 Refator

#41 케이크를 생성하고 수정한다.
  apps/client/package.json
  apps/client/src/App.css
  apps/client/src/App.tsx
  apps/client/src/assets/images/BananaCream.tsx
  apps/client/src/assets/images/BananaSheet.tsx
  apps/client/src/assets/images/BlueberryCream.tsx
  apps/client/src/assets/images/BlueberrySheet.tsx
  apps/client/src/assets/images/ChocoCream.tsx
  apps/client/src/assets/images/ChocoSheet.tsx
  apps/client/src/assets/images/MintCream.tsx
  apps/client/src/assets/images/MintSheet.tsx
  apps/client/src/assets/images/StrawberryCream.tsx
  apps/client/src/assets/images/StrawberrySheet.tsx
  apps/client/src/assets/images/WhiteCream.tsx
  apps/client/src/assets/images/WhiteSheet.tsx
  apps/client/src/assets/images/index.ts
  apps/client/src/components/Button.tsx
  apps/client/src/components/ColorSelector.tsx
  apps/client/src/components/RenderCake.tsx
  apps/client/src/components/Toggle.tsx
  apps/client/src/components/cake/CakeInfo.tsx
  apps/client/src/components/cake/MyCake.tsx
  apps/client/src/components/cake/SharedCake.tsx
  apps/client/src/components/letter/ChooseLetter.tsx
  apps/client/src/components/letter/WriteLetter.tsx
  apps/client/src/pages/Cake.tsx
  apps/client/src/pages/CreateCake.tsx
  apps/client/src/pages/CreateLetter.tsx
  apps/client/src/pages/Login.tsx
  apps/server/src/models/candle.ts
  apps/server/src/models/user.ts
  apps/server/src/routes/cake.ts
  apps/server/src/routes/candle.ts
  apps/server/src/service/cake.ts
  packages/types/src/cake.ts
  packages/types/src/index.ts
  packages/utils/src/checkType.ts
  packages/utils/src/index.ts
Labels: 🔧 Refator, ✨ Feature

#43 케이크 그리드 버전에 윈도잉 라이브러리를 적용한다
  apps/client/package.json
  apps/client/src/App.css
  apps/client/src/components/GridInfo.tsx
  apps/client/src/components/GridStyle.tsx
  apps/client/src/components/Wrapper.tsx
  apps/client/src/components/cake/MyCake.tsx
  apps/server/src/routes/cake.ts
  pnpm-lock.yaml
Labels: ✨ Feature

#45 refresh 토큰 db 검증 로직을 제거하다.
  apps/server/src/routes/auth.ts
  apps/server/src/service/auth.ts
  packages/database/prisma/schema.prisma
Labels: 📦 Chore

#46 윈도잉, 무한스크롤, 편지조회 기능을 구현한다.
  apps/client/package.json
  apps/client/src/components/GridInfo.tsx
  apps/client/src/components/cake/CakeInfo.tsx
  apps/client/src/components/letter/ReadLetter.tsx
  apps/client/src/pages/Cake.tsx
  apps/server/src/index.ts
  apps/server/src/routes/cake.ts
  apps/server/src/routes/letter.ts
  packages/schemas/src/cake.ts
  packages/schemas/src/index.ts
  packages/schemas/src/letter.ts
  packages/types/src/cake.ts
  packages/types/src/index.ts
  packages/types/src/letter.ts
  pnpm-lock.yaml
Labels: ✨ Feature

#47 장식초를 구매할 수 있고, 편지를 작성하면 포인트를 얻는다.
  apps/client/package.json
  apps/client/src/App.tsx
  apps/client/src/assets/icons/FacebookLogoIcon.tsx
  apps/client/src/assets/icons/KakaoLogoIcon.tsx
  apps/client/src/assets/icons/LinkIcon.tsx
  apps/client/src/assets/icons/index.ts
  apps/client/src/components/Button.tsx
  apps/client/src/components/ColorSelector.tsx
  apps/client/src/components/Wrapper.tsx
  apps/client/src/components/cake/MyCake.tsx
  apps/client/src/components/cake/SharedCake.tsx
  apps/client/src/components/letter/ChooseLetter.tsx
  apps/client/src/components/letter/WriteLetter.tsx
  apps/client/src/components/modal/LoginModal.tsx
  apps/client/src/components/modal/Modal.tsx
  apps/client/src/components/modal/ShareUrlModal.tsx
  apps/client/src/pages/ChooseCandle.tsx
  apps/client/src/pages/CreateCake.tsx
  apps/client/src/pages/CreateLetter.tsx
  apps/server/src/index.ts
  apps/server/src/models/candle.ts
  apps/server/src/models/letter.ts
  apps/server/src/models/user.ts
  apps/server/src/routes/candle.ts
  apps/server/src/routes/letter.ts
  apps/server/src/service/keyword.ts
  apps/server/src/service/letter.ts
  packages/database/package.json
  packages/database/prisma/schema.prisma
  packages/schemas/src/auth.ts
  packages/schemas/src/candle.ts
  packages/schemas/src/index.ts
  packages/schemas/src/letter.ts
  packages/types/src/candle.ts
  packages/types/src/letter.ts
  pnpm-lock.yaml
Labels: ✨ Feature

#50 자잘한 수정을 한다.
  apps/client/src/components/RenderCake.tsx
  apps/client/src/components/cake/CakeInfo.tsx
  apps/client/src/components/cake/Pagenation.tsx
  apps/client/src/components/letter/ReadLetter.tsx
Labels: 🐛 Bug, 📦 Chore

#51 버그를 해결한다.
  apps/client/src/components/cake/SharedCake.tsx
  apps/server/src/routes/letter.ts
  packages/eslint-config/react.js
Labels: 🐛 Bug, 📦 Chore

#53 Feature/share
  apps/client/public/apple-icon.png
  apps/client/public/favicon.png
  apps/client/public/index.html
  apps/client/src/assets/icons/FacebookLogoIcon.tsx
  apps/client/src/components/GridInfo.tsx
  apps/client/src/components/Loading.tsx
  apps/client/src/components/RenderCake.tsx
  apps/client/src/components/YearDropDown.tsx
  apps/client/src/components/cake/CakeInfo.tsx
  apps/client/src/components/cake/MyCake.tsx
  apps/client/src/components/cake/SharedCake.tsx
  apps/client/src/components/modal/ShareUrlModal.tsx
  apps/client/src/enviroment.d.ts
  apps/client/src/pages/Cake.tsx
  apps/client/src/pages/CreateCake.tsx
  apps/client/src/pages/CreateLetter.tsx
  apps/client/src/pages/GoogleLogin.tsx
  apps/client/src/pages/KakaoLogin.tsx
  apps/client/src/pages/Login.tsx
  apps/client/src/pages/Signup.tsx
  apps/client/webpack.config.dev.js
  apps/client/webpack.config.prod.js
  apps/server/src/routes/auth.ts
  apps/server/src/routes/cake.ts
  apps/server/src/routes/candle.ts
  apps/server/src/routes/letter.ts
  apps/server/src/service/auth.ts
  packages/database/prisma/schema.prisma
  packages/schemas/src/cake/requests.ts
  packages/schemas/src/cake/responses.ts
  packages/schemas/src/user/responses.ts
  packages/types/src/cake.ts
Labels: 🔧 Refator, ✨ Feature

#55 Feat: 클라이언트 환경 변수 github actions 주입
  .github/workflows/mainDeploy.yml
Labels: 📦 Chore

#56 에러를 고친다
  .github/workflows/mainDeploy.yml
  apps/client/src/components/cake/MyCake.tsx
  apps/client/src/pages/Cake.tsx
  apps/client/src/pages/Login.tsx
  apps/server/src/routes/user.ts
  apps/server/src/service/auth.ts
Labels: 🐛 Bug

#58 생일 편지 내용의 키워드를 AI로 추출한다.
  apps/client/package.json
  apps/client/src/components/Button.tsx
  apps/client/src/components/modal/Modal.tsx
  apps/client/src/components/modal/ShareUrlModal.tsx
  apps/client/src/pages/ChooseCandle.tsx
  apps/client/src/pages/CreateLetter.tsx
  apps/client/src/pages/Signup.tsx
  apps/server/package.json
  apps/server/src/enviroment.d.ts
  apps/server/src/service/keyword.ts
  packages/schemas/src/index.ts
  packages/schemas/src/keyword/responses.ts
  pnpm-lock.yaml
Labels: 🐛 Bug, 🖼️ Design, ✨ Feature

#60 FCM을 이용해 푸시 알림을 구현한다.
  .github/workflows/developPR.yml
  .github/workflows/mainDeploy.yml
  .github/workflows/mainPR.yml
  .gitignore
  apps/client/package.json
  apps/client/public/firebase-messaging-sw.js
  apps/client/src/enviroment.d.ts
  apps/client/src/firebase-messaging-sw.ts
  apps/client/src/pages/Signup.tsx
  apps/client/tsconfig.json
  apps/client/webpack.config.dev.js
  apps/client/webpack.config.prod.js
  apps/server/package.json
  apps/server/src/routes/letter.ts
  apps/server/src/routes/user.ts
  apps/server/tsconfig.json
  pnpm-lock.yaml
Labels: ✨ Feature

#61 푸시 알림을 구현한다.
  .github/workflows/developPR.yml
  .github/workflows/mainDeploy.yml
  .github/workflows/mainPR.yml
  .gitignore
  apps/client/package.json
  apps/client/public/firebase-messaging-sw.js
  apps/client/src/enviroment.d.ts
  apps/client/src/firebase-messaging-sw.ts
  apps/client/src/pages/Signup.tsx
  apps/client/tsconfig.json
  apps/client/webpack.config.dev.js
  apps/client/webpack.config.prod.js
  apps/server/package.json
  apps/server/src/routes/letter.ts
  apps/server/src/routes/user.ts
  apps/server/tsconfig.json
  pnpm-lock.yaml
Labels: ✨ Feature

#62 env를 추가한다
  .github/workflows/mainDeploy.yml
Labels: 🐛 Bug

#63 env 수정한다
  .github/workflows/mainDeploy.yml
Labels: 📦 Chore

#64 푸시 알림 로직을 수정한다.
  apps/client/src/App.tsx
  apps/client/src/firebase-messaging-sw.ts
  apps/client/src/pages/Signup.tsx
  pnpm-lock.yaml
Labels: 🐛 Bug

#65 라우트 기준으로 Lazy 로딩 / svg 외부 저장소 이동
  apps/client/package.json
  apps/client/src/App.tsx
  apps/client/src/assets/icons/KakaoLogoIcon.tsx
  apps/client/src/assets/images/BananaCream.tsx
  apps/client/src/assets/images/BananaSheet.tsx
  apps/client/src/assets/images/BlueberryCream.tsx
  apps/client/src/assets/images/BlueberrySheet.tsx
  apps/client/src/assets/images/ChocoCream.tsx
  apps/client/src/assets/images/ChocoSheet.tsx
  apps/client/src/assets/images/MintCream.tsx
  apps/client/src/assets/images/MintSheet.tsx
  apps/client/src/assets/images/StrawberryCream.tsx
  apps/client/src/assets/images/StrawberrySheet.tsx
  apps/client/src/assets/images/WhiteCream.tsx
  apps/client/src/assets/images/WhiteSheet.tsx
  apps/client/src/assets/images/index.ts
  apps/client/src/components/RenderCake.tsx
  apps/client/src/pages/Cake.tsx
  apps/client/src/pages/ChooseCandle.tsx
  apps/client/src/pages/CreateCake.tsx
  apps/client/src/pages/CreateLetter.tsx
  apps/client/src/pages/GoogleLogin.tsx
  apps/client/src/pages/KakaoLogin.tsx
  apps/client/src/pages/Login.tsx
  apps/client/src/pages/MyPage.tsx
  apps/client/src/pages/SignUp.tsx
  pnpm-lock.yaml
Labels: 📦 Chore

#66 알림 기능 버그 수정 및 svg외부 분리와 lazy loading 적용
  apps/client/package.json
  apps/client/src/App.tsx
  apps/client/src/assets/icons/KakaoLogoIcon.tsx
  apps/client/src/assets/images/BananaCream.tsx
  apps/client/src/assets/images/BananaSheet.tsx
  apps/client/src/assets/images/BlueberryCream.tsx
  apps/client/src/assets/images/BlueberrySheet.tsx
  apps/client/src/assets/images/ChocoCream.tsx
  apps/client/src/assets/images/ChocoSheet.tsx
  apps/client/src/assets/images/MintCream.tsx
  apps/client/src/assets/images/MintSheet.tsx
  apps/client/src/assets/images/StrawberryCream.tsx
  apps/client/src/assets/images/StrawberrySheet.tsx
  apps/client/src/assets/images/WhiteCream.tsx
  apps/client/src/assets/images/WhiteSheet.tsx
  apps/client/src/assets/images/index.ts
  apps/client/src/components/RenderCake.tsx
  apps/client/src/firebase-messaging-sw.ts
  apps/client/src/pages/Cake.tsx
  apps/client/src/pages/ChooseCandle.tsx
  apps/client/src/pages/CreateCake.tsx
  apps/client/src/pages/CreateLetter.tsx
  apps/client/src/pages/GoogleLogin.tsx
  apps/client/src/pages/KakaoLogin.tsx
  apps/client/src/pages/Login.tsx
  apps/client/src/pages/MyPage.tsx
  apps/client/src/pages/SignUp.tsx
  pnpm-lock.yaml
Labels: 🐛 Bug, 🔧 Refator, 📦 Chore, 🔥Performance

#67 컴포넌트 폴더 정리 및 임포트 경로 변경
  apps/client/src/components/__tests__/Button.test.tsx
  apps/client/src/components/cake/CakeInfo.tsx
  apps/client/src/components/cake/ColorSelector.tsx
  apps/client/src/components/cake/GridInfo.tsx
  apps/client/src/components/cake/GridStyle.tsx
  apps/client/src/components/cake/MyCake.tsx
  apps/client/src/components/cake/RenderCake.tsx
  apps/client/src/components/cake/SharedCake.tsx
  apps/client/src/components/common/Button.tsx
  apps/client/src/components/common/Input.tsx
  apps/client/src/components/common/Loading.tsx
  apps/client/src/components/common/Toggle.tsx
  apps/client/src/components/common/YearDropDown.tsx
  apps/client/src/components/layout/InnerWrapper.tsx
  apps/client/src/components/layout/Wrapper.tsx
  apps/client/src/components/modal/LoginModal.tsx
  apps/client/src/components/modal/ShareUrlModal.tsx
  apps/client/src/pages/Cake.tsx
  apps/client/src/pages/ChooseCandle.tsx
  apps/client/src/pages/CreateCake.tsx
  apps/client/src/pages/CreateLetter.tsx
  apps/client/src/pages/GoogleLogin.tsx
  apps/client/src/pages/KakaoLogin.tsx
  apps/client/src/pages/Login.tsx
  apps/client/src/pages/MyPage.tsx
  apps/client/src/pages/SignUp.tsx
  apps/client/src/test/example.test.tsx
Labels: 📦 Chore

#68 eslint rule을 추가한다.
  package.json
  packages/eslint-config/base.js
  packages/eslint-config/package.json
  pnpm-lock.yaml
Labels: 📦 Chore

#69 Fix: lazy loading 관련 에러 해결
  apps/client/src/App.tsx
  apps/client/src/assets/icons/KakaoLogoIcon.tsx
  apps/client/src/components/__tests__/Button.test.tsx
  apps/client/src/components/cake/CakeInfo.tsx
  apps/client/src/components/cake/ColorSelector.tsx
  apps/client/src/components/cake/GridInfo.tsx
  apps/client/src/components/cake/GridStyle.tsx
  apps/client/src/components/cake/MyCake.tsx
  apps/client/src/components/cake/RenderCake.tsx
  apps/client/src/components/cake/SharedCake.tsx
  apps/client/src/components/common/Button.tsx
  apps/client/src/components/common/Input.tsx
  apps/client/src/components/common/Loading.tsx
  apps/client/src/components/common/Toggle.tsx
  apps/client/src/components/common/YearDropDown.tsx
  apps/client/src/components/layout/InnerWrapper.tsx
  apps/client/src/components/layout/Wrapper.tsx
  apps/client/src/components/modal/LoginModal.tsx
  apps/client/src/components/modal/ShareUrlModal.tsx
  apps/client/src/pages/Cake.tsx
  apps/client/src/pages/ChooseCandle.tsx
  apps/client/src/pages/CreateCake.tsx
  apps/client/src/pages/CreateLetter.tsx
  apps/client/src/pages/GoogleLogin.tsx
  apps/client/src/pages/KakaoLogin.tsx
  apps/client/src/pages/Login.tsx
  apps/client/src/pages/MyPage.tsx
  apps/client/src/pages/SignUp.tsx
  apps/client/src/test/example.test.tsx
  package.json
  packages/eslint-config/base.js
  packages/eslint-config/package.json
  pnpm-lock.yaml
Labels: 🐛 Bug

#70 ios fcm 보류
  apps/client/src/firebase-messaging-sw.ts
Labels: 🐛 Bug

#71 react query를 적용한다
  apps/client/package.json
  apps/client/src/App.css
  apps/client/src/Normalize.css
  apps/client/src/apis/axios.ts
  apps/client/src/apis/cake/useGetCakeLetters.tsx
  apps/client/src/apis/cake/useGetGridLetters.tsx
  apps/client/src/components/cake/CakeInfo.tsx
  apps/client/src/components/cake/GridInfo.tsx
  apps/client/src/components/cake/SharedCake.tsx
  apps/client/src/index.tsx
  apps/client/src/pages/Cake.tsx
  apps/client/tsconfig.json
  packages/database/prisma/schema.prisma
  pnpm-lock.yaml
Labels: 🔧 Refator, ✨ Feature
